export const produtos = [
    { id: 1, nome: 'Laptop XYZ', preco: 194.68, categoria: 'Computadores' },
    { id: 2, nome: 'Mouse ABC', preco: 250.61, categoria: 'Acessórios' },
    { id: 3, nome: 'Teclado DEF', preco: 265.93, categoria: 'Acessórios' },
    { id: 4, nome: 'Monitor GHI', preco: 212.82, categoria: 'Monitores' },
    { id: 5, nome: 'Impressora JKL', preco: 227.54, categoria: 'Impressoras' },
    { id: 6, nome: 'Tablet MNO', preco: 70.05, categoria: 'Tablets' },
    { id: 7, nome: 'Smartphone PQR', preco: 192.8, categoria: 'Smartphones' },
    { id: 8, nome: 'Smartwatch STU', preco: 17.46, categoria: 'Wearables' },
    { id: 9, nome: 'Fone de Ouvido VWX', preco: 296.33, categoria: 'Acessórios' },
    { id: 10, nome: 'Roteador YZ', preco: 180.76, categoria: 'Redes' },
    { id: 11, nome: 'Disco Rígido Externo', preco: 41.72, categoria: 'Armazenamento' },
    { id: 12, nome: 'Câmera Digital', preco: 148.8, categoria: 'Câmeras' },
    { id: 13, nome: 'Projetor', preco: 148.71, categoria: 'Monitores' },
    { id: 14, nome: 'Dock Station', preco: 206.33, categoria: 'Acessórios' },
    { id: 15, nome: 'Microfone', preco: 246.95, categoria: 'Acessórios' },
    { id: 16, nome: 'Webcam', preco: 132.8, categoria: 'Câmeras' },
    { id: 17, nome: 'Carregador Portátil', preco: 36.78, categoria: 'Acessórios' },
    { id: 18, nome: 'Headset Gamer', preco: 168.64, categoria: 'Acessórios' },
    { id: 19, nome: 'Placa de Vídeo', preco: 230.3, categoria: 'Computadores' },
    { id: 20, nome: 'SSD Interno', preco: 18.04, categoria: 'Armazenamento' },
    { id: 21, nome: 'Pendrive', preco: 60.94, categoria: 'Armazenamento' },
    { id: 22, nome: 'Mouse Pad RGB', preco: 238.14, categoria: 'Acessórios' },
    { id: 23, nome: 'Teclado Mecânico', preco: 100.18, categoria: 'Acessórios' },
    { id: 24, nome: 'Hub USB', preco: 293.91, categoria: 'Acessórios' },
    { id: 25, nome: 'Switch de Rede', preco: 54.15, categoria: 'Redes' },
    { id: 26, nome: 'Estabilizador', preco: 179.33, categoria: 'Acessórios' },
    { id: 27, nome: 'Scanner', preco: 59.31, categoria: 'Impressoras' },
    { id: 28, nome: 'Cabo HDMI', preco: 145.97, categoria: 'Acessórios' },
    { id: 29, nome: 'Notebook Gamer', preco: 94.45, categoria: 'Computadores' },
    { id: 30, nome: 'Case para Smartphone', preco: 247.79, categoria: 'Acessórios' },
    { id: 31, nome: 'Adaptador Bluetooth', preco: 270.44, categoria: 'Acessórios' },
    { id: 32, nome: 'Antena Wi-Fi', preco: 257.17, categoria: 'Redes' },
    { id: 33, nome: 'Servidor NAS', preco: 143.97, categoria: 'Armazenamento' },
    { id: 34, nome: 'Controlador de Ventoinha', preco: 254.9, categoria: 'Acessórios' },
    { id: 35, nome: 'Cooler para CPU', preco: 198.92, categoria: 'Computadores' },
    { id: 36, nome: 'Bateria Externa', preco: 211.9, categoria: 'Acessórios' },
    { id: 37, nome: 'Leitor de Cartões', preco: 205.26, categoria: 'Acessórios' },
    { id: 38, nome: 'Antivírus', preco: 55.12, categoria: 'Software' },
    { id: 39, nome: 'Software de Edição de Vídeo', preco: 48.95, categoria: 'Software' },
    { id: 40, nome: 'Pacote Office', preco: 14.78, categoria: 'Software' },
    { id: 41, nome: 'Gamepad', preco: 81.06, categoria: 'Acessórios' },
    { id: 42, nome: 'Mouse Sem Fio', preco: 152.51, categoria: 'Acessórios' },
    { id: 43, nome: 'Cabo de Rede', preco: 109.68, categoria: 'Redes' },
    { id: 44, nome: 'Dock de Carregamento', preco: 64.89, categoria: 'Acessórios' },
    { id: 45, nome: 'Suporte para Monitor', preco: 115.54, categoria: 'Acessórios' },
    { id: 46, nome: 'Impressora Multifuncional', preco: 287.58, categoria: 'Impressoras' },
    { id: 47, nome: 'Modem', preco: 170.45, categoria: 'Redes' },
    { id: 48, nome: 'Adaptador USB-C', preco: 123.72, categoria: 'Acessórios' },
    { id: 49, nome: 'Estação Meteorológica', preco: 204.56, categoria: 'Acessórios' },
    { id: 50, nome: 'Suporte para Notebook', preco: 119.4, categoria: 'Acessórios' }
];